SELECT E1.ENAME,E1.SAL FROM EMP E1,EMP E2
WHERE E2.ENAME='SCOTT'
AND E2.SAL=E1.SAL;

SELECT E1.ENAME EMPLOYEE,E1.MGR,E2.ENAME MANAGER,E2.EMPNO FROM EMP E1,EMP E2
WHERE E1.MGR=E2.EMPNO;

SELECT E1.ENAME EMPLOYEE,E1.MGR,E1.HIREDATE,E2.ENAME MANAGER,E2.HIREDATE,E2.EMPNO FROM EMP E1,EMP E2
WHERE E1.MGR=E2.EMPNO
AND E1.HIREDATE<E2.HIREDATE;

SELECT E.ENAME,D.DEPTNO,D.DNAME,D.LOC FROM EMP E,DEPT D
WHERE E.DEPTNO(+)=D.DEPTNO;

--SUBQUERY

SELECT E1.* FROM EMP E1 WHERE SAL>(SELECT AVG(SAL) FROM EMP);

SELECT E.ENAME,E.DEPTNO,D.DNAME
FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
AND D.DEPTNO IN(SELECT DEPTNO FROM DEPT);

SELECT E.ENAME,D.DNAME,D.DEPTNO FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
AND E.SAL=(SELECT MAX(SAL) FROM EMP);

SELECT SAL FROM EMP ORDER BY SAL DESC;

SELECT ENAME,SAL FROM EMP
WHERE SAL IN(
SELECT MAX(SAL) FROM EMP
WHERE SAL<(SELECT MAX(SAL) FROM EMP));


SELECT JOB,ROUND(AVG(SAL)) AVERAGESAL FROM EMP
GROUP BY JOB
HAVING AVG(SAL)=(SELECT MIN(AVG(SAL)) FROM EMP GROUP BY JOB);


























